parameters:
    # Account
    bsp_accounting.account.class: BSP\AccountingBundle\Document\Account
    bsp_accounting.account_manager.class: BSP\AccountingBundle\Document\AccountManager

    # Financial Transaction
    bsp_accounting.financial_transaction.class: BSP\AccountingBundle\Document\FinacialTransaction
    bsp_accounting.financial_transaction_manager.class: BSP\AccountingBundle\Document\FinacialTransactionManager

    # MongoDB ID Generator Handler
    bsp_accounting.mongodb_handler.class: BSP\AccountingBundle\Handler\MongoDBAccountHandler

services:
    # Account
    bsp_accounting.account_manager:
        class: %bsp_accounting.account_manager.class%
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - %bsp_accounting.account.class%
            - @bsp_accounting.id_generator_provider

     # Financial Transaction
    bsp_accounting.financial_transaction_manager:
        class: %bsp_accounting.financial_transaction_manager.class%
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - %bsp_accounting.financial_transaction.class%

    # MongoDB ID Generator Handler
    bsp_accounting.mongodb_handler:
        class: %bsp_accounting.mongodb_handler.class%
        tags:
            - { name: bsp_accounting.account_handler }